# Generated by Django 3.0.6 on 2020-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_userprofileinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='name',
            new_name='COMPANY_NAME',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='bus_pic',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='front_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='BUSINESS_CARD_IMAGE',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='FRONT_INSIDE_PICTURE',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
